/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IHashi__factory } from "./IHashi__factory";
export { IOracleAdapter__factory } from "./IOracleAdapter__factory";
