/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface StorageVerifierInterface extends utils.Interface {
  functions: {};

  events: {
    "accountproofcomplete()": EventFragment;
    "storageproofcomplete()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "accountproofcomplete"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "storageproofcomplete"): EventFragment;
}

export interface accountproofcompleteEventObject {}
export type accountproofcompleteEvent = TypedEvent<
  [],
  accountproofcompleteEventObject
>;

export type accountproofcompleteEventFilter =
  TypedEventFilter<accountproofcompleteEvent>;

export interface storageproofcompleteEventObject {}
export type storageproofcompleteEvent = TypedEvent<
  [],
  storageproofcompleteEventObject
>;

export type storageproofcompleteEventFilter =
  TypedEventFilter<storageproofcompleteEvent>;

export interface StorageVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: StorageVerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "accountproofcomplete()"(): accountproofcompleteEventFilter;
    accountproofcomplete(): accountproofcompleteEventFilter;

    "storageproofcomplete()"(): storageproofcompleteEventFilter;
    storageproofcomplete(): storageproofcompleteEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
