/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  StorageVerifier,
  StorageVerifierInterface,
} from "../../contracts/StorageVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "p",
        type: "bytes32",
      },
    ],
    name: "Debug",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidStateProof",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidStorageProof",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [],
    name: "accountproofcomplete",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "storageproofcomplete",
    type: "event",
  },
] as const;

export class StorageVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): StorageVerifierInterface {
    return new utils.Interface(_abi) as StorageVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StorageVerifier {
    return new Contract(address, _abi, signerOrProvider) as StorageVerifier;
  }
}
