/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface IHashiInterface extends utils.Interface {
  functions: {
    "getHash(uint256,uint256,address[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getHash"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getHash",
    values: [BigNumberish, BigNumberish, string[]]
  ): string;

  decodeFunctionResult(functionFragment: "getHash", data: BytesLike): Result;

  events: {};
}

export interface IHashi extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IHashiInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getHash(
      domain: BigNumberish,
      id: BigNumberish,
      oracleAdapters: string[],
      overrides?: CallOverrides
    ): Promise<[string] & { hash: string }>;
  };

  getHash(
    domain: BigNumberish,
    id: BigNumberish,
    oracleAdapters: string[],
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getHash(
      domain: BigNumberish,
      id: BigNumberish,
      oracleAdapters: string[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getHash(
      domain: BigNumberish,
      id: BigNumberish,
      oracleAdapters: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getHash(
      domain: BigNumberish,
      id: BigNumberish,
      oracleAdapters: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
