/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface ClaimPenguinInterface extends utils.Interface {
  functions: {
    "claim(bytes32,uint256,string,bytes,bytes32,bytes32,bytes[],bytes[])": FunctionFragment;
    "getBlockHeader()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "claim" | "getBlockHeader"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claim",
    values: [
      BytesLike,
      BigNumberish,
      string,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBlockHeader",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBlockHeader",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ClaimPenguin extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ClaimPenguinInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    claim(
      hashiheader: BytesLike,
      tokenId: BigNumberish,
      image: string,
      signature: BytesLike,
      stateRoot: BytesLike,
      storageRoot: BytesLike,
      stateProof: BytesLike[],
      storageProof: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getBlockHeader(overrides?: CallOverrides): Promise<[string]>;
  };

  claim(
    hashiheader: BytesLike,
    tokenId: BigNumberish,
    image: string,
    signature: BytesLike,
    stateRoot: BytesLike,
    storageRoot: BytesLike,
    stateProof: BytesLike[],
    storageProof: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getBlockHeader(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    claim(
      hashiheader: BytesLike,
      tokenId: BigNumberish,
      image: string,
      signature: BytesLike,
      stateRoot: BytesLike,
      storageRoot: BytesLike,
      stateProof: BytesLike[],
      storageProof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    getBlockHeader(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    claim(
      hashiheader: BytesLike,
      tokenId: BigNumberish,
      image: string,
      signature: BytesLike,
      stateRoot: BytesLike,
      storageRoot: BytesLike,
      stateProof: BytesLike[],
      storageProof: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getBlockHeader(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    claim(
      hashiheader: BytesLike,
      tokenId: BigNumberish,
      image: string,
      signature: BytesLike,
      stateRoot: BytesLike,
      storageRoot: BytesLike,
      stateProof: BytesLike[],
      storageProof: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getBlockHeader(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
