/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IOracleAdapter,
  IOracleAdapterInterface,
} from "../IOracleAdapter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "blockNumber",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "reportedBlockHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "storedBlockHash",
        type: "bytes32",
      },
    ],
    name: "ConflictingBlockHeader",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "length",
        type: "uint256",
      },
    ],
    name: "InvalidBlockHeaderLength",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidBlockHeaderRLP",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "hashes",
        type: "bytes32",
      },
    ],
    name: "HashStored",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "domain",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "getHashFromOracle",
    outputs: [
      {
        internalType: "bytes32",
        name: "hash",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IOracleAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleAdapterInterface {
    return new utils.Interface(_abi) as IOracleAdapterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOracleAdapter {
    return new Contract(address, _abi, signerOrProvider) as IOracleAdapter;
  }
}
