/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { MPT, MPTInterface } from "../MPT";

const _abi = [
  {
    inputs: [],
    name: "InvalidAccount",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "InvalidProof",
    type: "error",
  },
];

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212200ae7276cf3a104e1382cee2d3f75d33a82644c6e73d13271a56c7da31b4f888664736f6c63430008110033";

export class MPT__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MPT> {
    return super.deploy(overrides || {}) as Promise<MPT>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MPT {
    return super.attach(address) as MPT;
  }
  connect(signer: Signer): MPT__factory {
    return super.connect(signer) as MPT__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MPTInterface {
    return new utils.Interface(_abi) as MPTInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): MPT {
    return new Contract(address, _abi, signerOrProvider) as MPT;
  }
}
