/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20PresetFixedSupply__factory } from "./ERC20PresetFixedSupply__factory";
export { ERC20PresetMinterPauser__factory } from "./ERC20PresetMinterPauser__factory";
